### ISSUE TITLE
Android: HelloCI-Android with Gradle not working - java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by FlorianKirmaier** [gluonhq/client-gradle-plugin#103]
To find out the issue with my android-build, I tried to implement your hello-gluon-ci project, as a gradle project.
After converting to android, the android-build doesn't work.
Check out my forked version for it: https://github.com/FlorianKirmaier/hello-gluon-ci
You can download the build from the github-action: https://github.com/FlorianKirmaier/hello-gluon-ci/actions/runs/602220167
It works for desktop and iOS

This is the error I get with `adb logcat`, when starting the application

```
02-26 10:20:00.717 25863 27898 D GraalCompiled: Exception in Application start method
02-26 10:20:00.717 25863 27898 D GraalCompiled: QuantumRenderer: shutdown
02-26 10:20:00.717 25863 27898 D GraalCompiled: Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
02-26 10:20:00.717 25863 27898 D GraalCompiled: 	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
02-26 10:20:00.717 25863 27898 D GraalCompiled: 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
02-26 10:20:00.717 25863 27898 D GraalCompiled: 	at java.lang.Thread.run(Thread.java:834)
02-26 10:20:00.717   548  6731 D gralloc : [mali_gralloc_allocate] begin
02-26 10:20:00.717   548  6731 D gralloc : buffer_descriptor: wh(1080 2019) usage_pc(0x40000000000b00 0x40000000000b00) hal_format(0x1) layer_count(1) sizes(0 0 0) strde(0) byte_stride(0) alloc_wh(0 0) internal_format(0x0) alloc_format(0x0) fd_count(1) plane_count(0)
02-26 10:20:00.717 25863 27898 D GraalCompiled: 	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
02-26 10:20:00.717 25863 27898 D GraalCompiled: 	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
02-26 10:20:00.717 25863 27898 D GraalCompiled: Caused by: java.lang.UnsatisfiedLinkError: no util in java.library.path
02-26 10:20:00.717 25863 27898 D GraalCompiled: 	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:132)
02-26 10:20:00.717 25863 27898 D GraalCompiled: 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:275)
02-26 10:20:00.717 25863 27898 D GraalCompiled: 	at java.lang.Runtime.loadLibrary0(Runtime.java:830)
02-26 10:20:00.717 25863 27898 D GraalCompiled: 	at java.lang.System.loadLibrary(System.java:1871)
02-26 10:20:00.717 25863 27898 D GraalCompiled: 	at com.gluonhq.attach.util.Platform.<clinit>(Platform.java:81)
02-26 10:20:00.718 25863 27898 D GraalCompiled: 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
02-26 10:20:00.718 25863 27898 D GraalCompiled: 	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
02-26 10:20:00.718 25863 27898 D GraalCompiled: 	at com.gluonhq.attach.util.impl.DefaultServiceFactory.getInstance(DefaultServiceFactory.java:56)
02-26 10:20:00.718 25863 27898 D GraalCompiled: 	at com.gluonhq.attach.util.Services.get(Services.java:85)
02-26 10:20:00.718 25863 27898 D GraalCompiled: 	at com.gluonhq.attach.display.DisplayService.create(DisplayService.java:95)
02-26 10:20:00.718 25863 27898 D GraalCompiled: 	at com.gluonhq.impl.charm.glisten.util.DeviceSettings.hasNotch(DeviceSettings.java:27)
02-26 10:20:00.718 25863 27898 D GraalCompiled: 	at com.gluonhq.impl.charm.glisten.util.DeviceSettings.setup(DeviceSettings.java:45)
02-26 10:20:00.718 25863 27898 D GraalCompiled: 	at com.gluonhq.impl.charm.glisten.util.DeviceSettings.dedicatedSetup(DeviceSettings.java:38)
02-26 10:20:00.718 25863 27898 D GraalCompiled: 	at com.gluonhq.charm.glisten.control.AppBar.<init>(AppBar.java:127)
02-26 10:20:00.718 25863 27898 D GraalCompiled: 	at com.gluonhq.charm.glisten.application.MobileApplication.start(MobileApplication.java:202)
02-26 10:20:00.718 25863 27898 D GraalCompiled: 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
02-26 10:20:00.718 25863 27898 D GraalCompiled: 	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
02-26 10:20:00.718 25863 27898 D GraalCompiled: 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
02-26 10:20:00.718 25863 27898 D GraalCompiled: 	at java.security.AccessController.doPrivileged(AccessController.java:102)
02-26 10:20:00.718 25863 27898 D GraalCompiled: 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
02-26 10:20:00.718 25863 27898 D GraalCompiled: 	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
02-26 10:20:00.718 25863 27898 D GraalCompiled: 	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
02-26 10:20:00.718 25863 27898 D GraalCompiled: 	... 3 more
```

**Comment by jperedadnr** [comment]
You need to translate the `attachList` from [here](https://github.com/FlorianKirmaier/hello-gluon-ci/blob/master/pom.xml#L94), and for that you need to use the  `attachConfig` extension to define the Attach services, like:

```
gluonClient {
    target = "android"
    attachConfig {
        version = "4.0.10"
        services 'display', 'lifecycle', 'statusbar', 'storage'
    }
```

All possible extensions are defined here: https://github.com/gluonhq/client-gradle-plugin/blob/master/src/main/java/com/gluonhq/gradle/ClientExtension.java

**Comment by FlorianKirmaier** [comment]
@jperedadnr 
Can't confirm it's working with this change.
By the way, the hello-gluon-ci project was a huge win for your users.
My recommendation would be to make a second hello-ci project for Gradle, just to make sure there are no errors. 
It would make it easier to be sure everything is fine, both for you and your users.

**Comment by jperedadnr** [comment]
What exception do you get?

Since `attachConfig` already manages all Attach dependencies you don't need to include them, just:

```
dependencies {
    implementation "com.gluonhq:charm-glisten:6.0.6"
}
```

**Comment by FlorianKirmaier** [comment]
Hm, but strangely it works well for iOS. And for Android, it also doesn't work when I mention them the way you've suggested.

Just to mention it, I've now got a working setup. For iOS, I use Gradle, and for Android, I create a fat-jar with Gradle and then use maven. This is ugly but works for now. The only issue left is the PasswordFiel problem for android https://github.com/gluonhq/substrate/issues/885

By the way, it would be great to have an option, to print the generated log files. Very time-consuming to check the output for logfiles to print in the next run of the ci build.


That's the error:

https://github.com/FlorianKirmaier/hello-gluon-ci/runs/2007783586?check_suite_focus=true
```

[Mon Mar 01 21:27:12 UTC 2021][INFO] [SUB] [com.gluonhq.hello.hellogluonapp:6546]      [total]: 267,663.55 ms,  3.90 GB
[Mon Mar 01 21:27:14 UTC 2021][INFO] [SUB] /usr/bin/ld: /home/runner/.gluon/substrate/javafxStaticSdk/16-ea+gvm31/linux-x86_64/sdk/lib/libgstreamer-lite.a(gstiirequalizer.o): undefined reference to symbol 'floorf@@GLIBC_2.2.5'

[Mon Mar 01 21:27:14 UTC 2021][INFO] [SUB] /lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
> Task :nativeLink FAILED
[Mon Mar 01 21:27:14 UTC 2021][INFO] [SUB] collect2: error: ld returned 1 exit status
[Mon Mar 01 21:27:13 UTC 2021][INFO] ==================== LINK TASK ====================
```

**Comment by jperedadnr** [comment]
That error you are posting doesn't relate to Attach, it shows `linux-x86_64`, which shouldn't be there.

You are using `./gradlew -Pandroid ...native...`, that doesn't work with Gradle (unless you create a project property), you need to set the target:

```
gluonClient {
    target = "android"
...
}
```
