### ISSUE TITLE
Accelerators don't work

### ISSUE THREAD

**Issue by hallvard** [gluonhq/client-gradle-plugin#14]
I tried using `accelerator="Meta+N"` in FXML menu items, which normally works, but when running natively (it compiled without issues) I got an error message about cannot coerce "Meta+N" to <some class I don't remember>.

**Comment by hallvard** [comment]
Here's the stack trace:
```
[SUB] Caused by: java.lang.IllegalArgumentException: Unable to coerce Meta+N to class javafx.scene.input.KeyCombination.
[SUB]   at com.sun.javafx.fxml.BeanAdapter.coerce(BeanAdapter.java:496)
[SUB]   at com.sun.javafx.fxml.BeanAdapter.put(BeanAdapter.java:258)
[SUB]   at com.sun.javafx.fxml.BeanAdapter.put(BeanAdapter.java:54)
[SUB]   at javafx.fxml.FXMLLoader$Element.applyProperty(FXMLLoader.java:520)
[SUB]   at javafx.fxml.FXMLLoader$Element.processValue(FXMLLoader.java:370)
[SUB]   at javafx.fxml.FXMLLoader$Element.processPropertyAttribute(FXMLLoader.java:332)
[SUB]   at javafx.fxml.FXMLLoader$Element.processInstancePropertyAttributes(FXMLLoader.java:242)
[SUB]   at javafx.fxml.FXMLLoader$ValueElement.processEndElement(FXMLLoader.java:775)
[SUB]   at javafx.fxml.FXMLLoader.processEndElement(FXMLLoader.java:2838)
[SUB]   at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2557)
[SUB]   ... 10 more
[SUB] Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
```

**Comment by hallvard** [comment]
In BeanAdapter the following line tries to find a valueOf method that can be used:
`valueOfMethod = type.getDeclaredMethod(VALUE_OF_METHOD_NAME, valueType);`
valueType will here be `String` and type `javafx.scene.input.KeyCombination`. `javafx.scene.input.KeyCombination` has a `valueOf` method taking a (single) `String` argument, so it should find the method. When it doesn't, the above exception is thrown.
