### ISSUE TITLE
Cannot find class MacAccessible

### ISSUE THREAD

**Issue by hallvard** [gluonhq/client-gradle-plugin#15]
When running natively (with gradle runNative) I get lots of error messages like this:
java.lang.NoClassDefFoundError: Could not initialize class com.sun.glass.ui.mac.MacAccessible

```
[SUB] Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: Could not initialize class com.sun.glass.ui.mac.MacAccessible
[SUB]   at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:214)
[SUB]   at java.lang.Class.ensureInitialized(DynamicHub.java:451)
[SUB]   at com.sun.glass.ui.mac.MacApplication.createAccessible(MacApplication.java:259)
[SUB]   at javafx.scene.Scene.getAccessible(Scene.java:6440)
[SUB]   at javafx.scene.Scene$ScenePeerListener.getSceneAccessible(Scene.java:2869)
[SUB]   at com.sun.javafx.tk.quantum.GlassViewEventHandler.getSceneAccessible(GlassViewEventHandler.java:1376)
[SUB]   at com.sun.glass.ui.View.getAccessible(View.java:1117)
[SUB]   at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Lcom_sun_glass_ui_View_2_0002egetAccessible_00028_00029J(JNIJavaCallWrappers.java:0)
```

**Comment by jperedadnr** [comment]
Whenever you get something like that, you can try to add that class to one of the available lists documented [here](https://docs.gluonhq.com/client/#_4_gluonclient_extension_2). 

In this case the error mentions initialization issues, so you can try:
```
gluonClient {
   ...
   delayInitList = [ "com.sun.glass.ui.mac.MacAccessible" ]
}
```
and try again.

**Comment by hallvard** [comment]
The documentation doesn't really explain the meaning, it just says "delayed initialization list". Is it about delaying (static) initialisation of classes? In this case it's triggered by a call to createAccessible, so how can it be delayed more? The app works, though, it's not a severe issue.

**Comment by xberkhout** [comment]
It seems there are more classes missing (like TableColumnBase). Should you just run it, see all classes that are missing when running natively and then  add them with delayInitList?
