### ISSUE TITLE
HelloFX Compiling Error

### ISSUE THREAD

**Issue by amcquistan** [gluonhq/client-gradle-plugin#43]
When trying to compile the HelloFX sample project targeting the Mac desktop I get a compiler error when running

```
./gradlew nativeCompile
```

The Java app runs fine with `./gradlew run`

I am using OpenJDK 11.0.2

```
$ java --version
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

llvm / clang 6.0.0

```
$ clang --version
clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Users/adammcquistan/Code/clang+llvm-6.0.0-x86_64-apple-darwin/bin
```

Here is the output of `./gradlew nativeCompile`

```
$ ./gradlew nativeCompile

> Task :nativeCompile
Omega :: host triplet = x86_64-macos-macos
Omega :: target triplet = x86_64-macos-macos

[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB] [HelloFX:22987]    classlist:   7,298.98 ms
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB] WARNING: An illegal reflective access operation has occurred
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB] WARNING: Illegal reflective access by com.oracle.svm.util.ReflectionUtil (file:/Users/adammcquistan/.gluon/omega/graalLibs/20.0.0-ea+12/bundle/lib/svm/builder/pointsto.jar) to field java.nio.file.Files$FileTypeDetectors.installedDetectors
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB] WARNING: Please consider reporting this to the maintainers of com.oracle.svm.util.ReflectionUtil
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB] WARNING: All illegal access operations will be denied in a future release
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB] [HelloFX:22987]        setup:     702.78 ms
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB] Error: Error parsing JNI configuration in /Users/adammcquistan/Code/java/client-samples/Gradle/HelloFX/build/client/macos-x86_64/gvm/jniconfig-ios.json:
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB] Class com.sun.glass.ui.ios.IosApplication not found
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB] Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option JNIConfigurationFiles.
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB] com.oracle.svm.core.util.UserError$UserException: Error parsing JNI configuration in /Users/adammcquistan/Code/java/client-samples/Gradle/HelloFX/build/client/macos-x86_64/gvm/jniconfig-ios.json:
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB] Class com.sun.glass.ui.ios.IosApplication not found
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB] Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option JNIConfigurationFiles.
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB]      at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB]      at com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:108)
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB]      at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$0(ConfigurationParserUtils.java:75)
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB]      at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB]      at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB]      at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB]      at com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:69)
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB]      at com.oracle.svm.jni.access.JNIAccessFeature.afterRegistration(JNIAccessFeature.java:122)
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$11(NativeImageGenerator.java:811)
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB]      at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:811)
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:521)
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[Sun Aug 25 22:17:29 CDT 2019][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

> Task :nativeCompile
java.lang.RuntimeException: Error compiling
        at com.gluonhq.omega.SVMBridge.compile(SVMBridge.java:311)
        at com.gluonhq.omega.target.IosTargetProcess.compileApplication(IosTargetProcess.java:225)
        at com.gluonhq.omega.target.AbstractTargetProcess.compile(AbstractTargetProcess.java:318)
        at com.gluonhq.omega.Omega.nativeCompile(Omega.java:72)
        at com.gluonhq.gradle.tasks.ConfigBuild.build(ConfigBuild.java:160)
        at com.gluonhq.gradle.tasks.ClientNativeCompile.action(ClientNativeCompile.java:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:701)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:668)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$4.run(ExecuteActionsTaskExecuter.java:337)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:326)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:311)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:75)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:158)
        at org.gradle.internal.execution.impl.steps.ExecuteStep.execute(ExecuteStep.java:46)
        at org.gradle.internal.execution.impl.steps.CancelExecutionStep.execute(CancelExecutionStep.java:34)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:69)
        at org.gradle.internal.execution.impl.steps.TimeoutStep.execute(TimeoutStep.java:49)
        at org.gradle.internal.execution.impl.steps.CatchExceptionStep.execute(CatchExceptionStep.java:34)
        at org.gradle.internal.execution.impl.steps.CreateOutputsStep.execute(CreateOutputsStep.java:49)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:42)
        at org.gradle.internal.execution.impl.steps.SnapshotOutputStep.execute(SnapshotOutputStep.java:28)
        at org.gradle.internal.execution.impl.steps.CacheStep.executeWithoutCache(CacheStep.java:136)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:60)
        at org.gradle.internal.execution.impl.steps.CacheStep.execute(CacheStep.java:37)
        at org.gradle.internal.execution.impl.steps.PrepareCachingStep.execute(PrepareCachingStep.java:33)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:38)
        at org.gradle.internal.execution.impl.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:23)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:95)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:88)
        at java.base/java.util.Optional.map(Optional.java:265)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:52)
        at org.gradle.internal.execution.impl.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:34)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ResolveIncrementalChangesTaskExecuter.execute(ResolveIncrementalChangesTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:92)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:75)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:46)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:834)

BUILD SUCCESSFUL in 12s
3 actionable tasks: 3 executed
```

Please let me know if there is any other information that I can provide to help solve this issue.

**Comment by amcquistan** [comment]
Sorry, false alarm. Easy fix found by running

```
./gradlew build nativeCompile
```

then things went fine
