### ISSUE TITLE
HotSpotJVMCICompilerFactory.getCompilationLevelAdjustment() is no longer supported

### ISSUE THREAD

**Issue by tlvenn** [gluonhq/client-gradle-plugin#54]
Hi,

I am trying to compile natively a very simple hello javafx done in kotlin with TornadoFX using the latest Graalvm release.
I am running into this error though:

```
> Task :nativeCompile
Omega :: host triplet = x86_64-macos-macos
Omega :: target triplet = x86_64-macos-macos

[Thu Nov 28 18:17:34 AEST 2019][INFO] [SUB] Exception in thread "main" java.lang.UnsupportedOperationException: jdk.vm.ci.hotspot.HotSpotJVMCICompilerFactory.getCompilationLevelAdjustment() is no longer supported. Use jdk.vm.ci.hotspot.HotSpotJVMCICompilerFactory.excludeFromJVMCICompil
ation() instead.
[Thu Nov 28 18:17:34 AEST 2019][INFO] [SUB]     at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.<init>(HotSpotJVMCIRuntime.java:475)
[Thu Nov 28 18:17:34 AEST 2019][INFO] [SUB]     at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.runtime(HotSpotJVMCIRuntime.java:172)
[Thu Nov 28 18:17:34 AEST 2019][INFO] [SUB]     at jdk.internal.vm.ci/jdk.vm.ci.runtime.JVMCI.initializeRuntime(Native Method)
[Thu Nov 28 18:17:34 AEST 2019][INFO] [SUB]     at jdk.internal.vm.ci/jdk.vm.ci.runtime.JVMCI.getRuntime(JVMCI.java:65)
[Thu Nov 28 18:17:34 AEST 2019][INFO] [SUB]     at com.oracle.svm.hosted.c.GraalAccess.getGraalCapability(GraalAccess.java:50)
[Thu Nov 28 18:17:34 AEST 2019][INFO] [SUB]     at com.oracle.svm.hosted.c.GraalAccess.getOriginalTarget(GraalAccess.java:38)
[Thu Nov 28 18:17:34 AEST 2019][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.isValidArchitecture(NativeImageGeneratorRunner.java:178)
[Thu Nov 28 18:17:34 AEST 2019][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.verifyValidJavaVersionAndPlatform(NativeImageGeneratorRunner.java:365)
[Thu Nov 28 18:17:34 AEST 2019][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:189)
[Thu Nov 28 18:17:34 AEST 2019][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:446)
[Thu Nov 28 18:17:34 AEST 2019][INFO] [SUB]     at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:112)
```
 
Could it be that #53 is needed to make this work ?

**Comment by waicool20** [comment]
I am also getting this error, any updates?

**Comment by tlvenn** [comment]
@johanvos it would be great to have some feedback on this. I bough your book and the chapter 10 on native image with Graal / Gradle simply cant work because it uses this plugin which does not work anymore with the recent version of openjdk / javafx.

Thanks in advance for your help.
