### ISSUE TITLE
Run fails after successful gradle nativeBuild on Windows

### ISSUE THREAD

**Issue by phamvanthanh** [gluonhq/client-gradle-plugin#76]
Hi
It was fine when build with maven but this is what I got when build with gradle.

PS F:\client-samples-master\Maven\HelloFX\build\client\x86_64-windows> .\hellofx
Exception in thread "main" java.lang.RuntimeException: Application launch error
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:202)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
Caused by: java.lang.AssertionError: java.lang.ClassNotFoundException: javafx.scene.image.Image
        at com.sun.javafx.util.Utils.forceInit(Utils.java:858)
        at com.sun.javafx.tk.Toolkit.<clinit>(Toolkit.java:944)
        at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
        at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
        at java.lang.Class.ensureInitialized(DynamicHub.java:499)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: javafx.scene.image.Image
        at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
        at java.lang.Class.forName(DynamicHub.java:1207)
        at com.sun.javafx.util.Utils.forceInit(Utils.java:855)
        ... 12 more

**Comment by tiainen** [comment]
The gradle plugin does not yet include support for the windows platform. It needs an update to use substrate 0.0.22, which is tracked in https://github.com/gluonhq/client-gradle-plugin/issues/75
