### ISSUE TITLE
Native Image has a fxml load exception [Windows]

### ISSUE THREAD

**Issue by vgroenewold** [gluonhq/client-gradle-plugin#90]
So I'm using this plugin to try and build a native-image. I work in IntelliJ and there my project runs fine. Making an executable jar also works just fine (I had an issue with the runtime classpath which was solved). Building a native image also works (using the x64 developer shell), but it doesn't launch, with a loadexception of my main fxml. It doesn't mention "location not set" so I'm assuming it can actually locate it (and thus has a correct runtime classpath?), but has another fault. I'm thinking I need another setting for the gluonClient{} block which I'm unaware off. Any ideas? Thank you!

This is my build.gradle;

```
plugins {
    id 'java'
    id 'application'
    id 'distribution'
    id 'org.openjfx.javafxplugin' version '0.0.9'
    id 'com.gluonhq.client-gradle-plugin' version '0.1.31'
    id 'org.beryx.jlink' version '2.12.0'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation('junit:junit:4.13')
}

group 'com.ariesproductions'
version '1.0-SNAPSHOT'
sourceCompatibility = 11
mainClassName = 'com.astropixelprocessor.Main'

javafx {
    version = '15'
    modules = ['javafx.controls', 'javafx.fxml']
}

gluonClient {
    reflectionList = ["com.astropixelprocessor.APP"]
}

jar {
    manifest {
        attributes 'Main-Class': 'com.astropixelprocessor.Main'
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
```

This is the error;

```
[Fri Oct 02 19:34:12 CEST 2020][INFO] ==================== RUN TASK ====================
[Fri Oct 02 19:34:12 CEST 2020][FINE] PB Command for run until end: C:\Users\vince\Documents\Company\Company-APP\Programming\Java\Projects\AstroPixelProcessor-javafx\build\client\x86_64-windows\AstroPixelProcessor-javafx.exe
[Fri Oct 02 19:34:12 CEST 2020][FINE] Start process run until end...
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] There was a problem loading the main view fxml; javafx.fxml.LoadException: 
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] views/MainView.fxml
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] 
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] Exception in Application start method
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] Something went wrong with launching the JavaFX runtime.
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] java.lang.RuntimeException: Exception in Application start method
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] 	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] 	at java.lang.Thread.run(Thread.java:834)
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] 	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] 	at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] Caused by: java.lang.NullPointerException
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] 	at com.astropixelprocessor.APP.start(APP.java:41)
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] 	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] 	at java.security.AccessController.doPrivileged(AccessController.java:101)
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] 	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_Runnable_2_0002erun_00028_00029V(JNIJavaCallWrappers.java:0)
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] 	at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] 	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
[Fri Oct 02 19:34:12 CEST 2020][FINE] [SUB] 	... 3 more
[Fri Oct 02 19:34:12 CEST 2020][FINE] Result for run until end: 0
```

**Comment by h4ckm3-id** [comment]
first 
create folder on ur resources  called 'META-INF' and inside that make another folder 'native-image'
and add this on ur build.gradle :
```

run {
    jvmArgs=["-agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image"]
}

```
after that Run that run task first, then do gradlew nativeBuild on terminal .

No more class error and manual reflectionList input ^_^

**Comment by vgroenewold** [comment]
Sorry for not coming back to you sooner. But thanks a lot for that insight! I am wondering though, as a bit of a beginner, how does this avoid having to have a reflectionList? Some of these solution still look like magic to me. ;)

**Comment by mipastgt** [comment]
That is because the native-image-agent generates such reflection (and other) lists for you in the given config-merge-dir, which is then used during the actual native image build.

**Comment by vgroenewold** [comment]
Ok, interesting. As it was different from what one of the developers told me to do, this seems way easier then re-running the code just to find out which classes need to be added. That did give me some more insight ofcourse, but nice to have this as well. Thanks!
